/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Basic health check
         * @description Returns the basic health status of the API service.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database health check
         * @description Checks the connectivity and latency of the database connection.
         */
        get: operations["database_health_check_api_v1_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storage health check
         * @description Checks the availability and write permissions of the file storage service.
         */
        get: operations["storage_health_check_api_v1_health_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's documentation sessions
         * @description Retrieves a paginated list of documentation sessions for the authenticated user. Supports filtering by session status.
         */
        get: operations["get_sessions_api_v1_sessions_get"];
        put?: never;
        /**
         * Create a new documentation session
         * @description Creates a new documentation session for the authenticated user. A session represents a complete workflow from audio upload to document confirmation.
         */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session details
         * @description Retrieves detailed information about a specific documentation session, including the presence of audio, transcript, and medical document.
         */
        get: operations["get_session_details_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download audio file for a session
         * @description Retrieves and downloads the audio file associated with a documentation session.
         */
        get: operations["get_audio_api_v1_sessions__session_id__audio_get"];
        put?: never;
        /**
         * Upload audio file for a session
         * @description Uploads an audio file to a documentation session. The session must be in 'created' state. Supports common audio formats (MP3, WAV, M4A, etc.).
         */
        post: operations["upload_audio_api_v1_sessions__session_id__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start audio transcription
         * @description Starts the transcription process for the audio file associated with a session. The transcription runs in the background. The session must have an uploaded audio file.
         */
        post: operations["transcribe_audio_api_v1_sessions__session_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transcript for a session
         * @description Retrieves the transcript text and metadata for a session. The transcript must exist (transcription must be completed).
         */
        get: operations["get_transcript_api_v1_sessions__session_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List medical document templates
         * @description Retrieves a paginated list of medical document templates. Can filter to show only active templates.
         */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get template details
         * @description Retrieves detailed information about a specific medical document template, including all its fields.
         */
        get: operations["get_template_details_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate medical document
         * @description Generates a medical document from the transcript and clinical facts. The session must have a completed transcription and extracted clinical facts.
         */
        post: operations["generate_document_api_v1_sessions__session_id__document_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_sessions__session_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Field */
        put: operations["update_field_api_v1_sessions__session_id__document_fields__field_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate Document */
        get: operations["validate_document_api_v1_sessions__session_id__document_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Document */
        post: operations["confirm_document_api_v1_sessions__session_id__document_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/document/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Document */
        post: operations["export_document_api_v1_sessions__session_id__document_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioUploadResponse */
        AudioUploadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** File Name */
            file_name: string;
            /** File Size */
            file_size: number;
            /** Duration */
            duration: number;
            /** Format */
            format: string;
            /** Uploaded At */
            uploaded_at: string;
        };
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token: components["schemas"]["TokenResponse"];
        };
        /** Body_upload_audio_api_v1_sessions__session_id__audio_post */
        Body_upload_audio_api_v1_sessions__session_id__audio_post: {
            /** File */
            file: string;
        };
        /** ConfirmDocumentResponse */
        ConfirmDocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["MedicalDocumentStatus"];
            /** Message */
            message: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
        };
        /**
         * DocumentationSessionStatus
         * @enum {string}
         */
        DocumentationSessionStatus: "created" | "audio_uploaded" | "transcribed" | "facts_extracted" | "draft_created" | "confirmed";
        /** ExportDocumentRequest */
        ExportDocumentRequest: {
            /**
             * Format
             * @default json
             */
            format: string;
        };
        /** ExportDocumentResponse */
        ExportDocumentResponse: {
            /** Task Id */
            task_id: string;
            /** Message */
            message: string;
        };
        /** FieldValueDTO */
        FieldValueDTO: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Name */
            field_name: string;
            /** Field Label */
            field_label: string;
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Is Required */
            is_required: boolean;
            /** Confidence */
            confidence?: number | null;
            /** Source Text */
            source_text?: string | null;
            /** Source Start Index */
            source_start_index?: number | null;
            /** Source End Index */
            source_end_index?: number | null;
        };
        /** GenerateDocumentRequest */
        GenerateDocumentRequest: {
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
        };
        /** GenerateDocumentResponse */
        GenerateDocumentResponse: {
            /** Task Id */
            task_id: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MedicalDocumentDetailsResponse */
        MedicalDocumentDetailsResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Template Name */
            template_name: string;
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /** Transcript Text */
            transcript_text: string;
            status: components["schemas"]["MedicalDocumentStatus"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Field Values */
            field_values: components["schemas"]["FieldValueDTO"][];
            /** Validation Status */
            validation_status: {
                [key: string]: boolean;
            };
        };
        /**
         * MedicalDocumentStatus
         * @enum {string}
         */
        MedicalDocumentStatus: "pending" | "confirmed";
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /** SessionDetailsResponse */
        SessionDetailsResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            status: components["schemas"]["DocumentationSessionStatus"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Has Audio
             * @default false
             */
            has_audio: boolean;
            /**
             * Has Transcript
             * @default false
             */
            has_transcript: boolean;
            /**
             * Has Document
             * @default false
             */
            has_document: boolean;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionResponse"][];
            /** Total */
            total: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            status: components["schemas"]["DocumentationSessionStatus"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** TemplateDetailsResponse */
        TemplateDetailsResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Version */
            version: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Fields */
            fields: components["schemas"]["TemplateFieldDTO"][];
        };
        /** TemplateFieldDTO */
        TemplateFieldDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Is Required */
            is_required: boolean;
            /** Default Value */
            default_value?: string | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            /** Order */
            order: number;
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateResponse"][];
            /** Total */
            total: number;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Version */
            version: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TranscribeRequest */
        TranscribeRequest: {
            /** @default ru */
            language: components["schemas"]["TranscriptLanguage"];
        };
        /** TranscribeResponse */
        TranscribeResponse: {
            /** Task Id */
            task_id: string;
            /** Message */
            message: string;
        };
        /**
         * TranscriptLanguage
         * @enum {string}
         */
        TranscriptLanguage: "ru";
        /** TranscriptResponse */
        TranscriptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Audio Record Id
             * Format: uuid
             */
            audio_record_id: string;
            /** Text */
            text: string;
            language: components["schemas"]["TranscriptLanguage"];
            /** Confidence Score */
            confidence_score: number;
            /** Created At */
            created_at: string;
        };
        /** UpdateFieldRequest */
        UpdateFieldRequest: {
            /** Value */
            value: string;
        };
        /** UpdateFieldResponse */
        UpdateFieldResponse: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Value */
            value: string;
            /** Status */
            status: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ValidateDocumentResponse */
        ValidateDocumentResponse: {
            /** Is Valid */
            is_valid: boolean;
            /** Missing Fields */
            missing_fields: string[];
            /** Doubtful Fields */
            doubtful_fields: string[];
            /** Required Fields Count */
            required_fields_count: number;
            /** Filled Fields Count */
            filled_fields_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    database_health_check_api_v1_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | number;
                    };
                };
            };
        };
    };
    storage_health_check_api_v1_health_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage is available and writable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy",
                     *       "timestamp": "2024-01-15T10:00:00Z",
                     *       "storage_status": "available",
                     *       "storage_path": "/path/to/storage"
                     *     }
                     */
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
            /** @description Storage is unavailable or read-only */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unhealthy",
                     *       "timestamp": "2024-01-15T10:00:00Z",
                     *       "storage_status": "unavailable",
                     *       "error": "Storage path does not exist: /path/to/storage"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                /** @description Maximum number of sessions to return (1-1000) */
                limit?: number;
                /** @description Number of sessions to skip for pagination */
                offset?: number;
                /** @description Filter sessions by status (created, audio_uploaded, transcribed, draft_created, confirmed) */
                status?: components["schemas"]["DocumentationSessionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_details_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_api_v1_sessions__session_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_audio_api_v1_sessions__session_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_api_v1_sessions__session_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_audio_api_v1_sessions__session_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_v1_sessions__session_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                /** @description Filter to show only active templates */
                active_only?: boolean;
                /** @description Maximum number of templates to return (1-1000) */
                limit?: number;
                /** @description Number of templates to skip for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_details_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_api_v1_sessions__session_id__document_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_sessions__session_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicalDocumentDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_field_api_v1_sessions__session_id__document_fields__field_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFieldRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateFieldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_document_api_v1_sessions__session_id__document_validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_document_api_v1_sessions__session_id__document_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_api_v1_sessions__session_id__document_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
