from . import audio_record_repository_protocol as audio_record_repository_protocol
from . import clinical_fact_repository_protocol as clinical_fact_repository_protocol
from . import documentation_session_repository_protocol as documentation_session_repository_protocol
from . import medical_document_repository_protocol as medical_document_repository_protocol
from . import template_repository_protocol as template_repository_protocol
from . import transcript_repository_protocol as transcript_repository_protocol
from . import user_repository_protocol as user_repository_protocol
from .audio_record_repository_protocol import AudioRecordRepositoryProtocol
from .clinical_fact_repository_protocol import ClinicalFactRepositoryProtocol
from .documentation_session_repository_protocol import DocumentationSessionRepositoryProtocol
from .medical_document_repository_protocol import MedicalDocumentRepositoryProtocol
from .template_repository_protocol import TemplateRepositoryProtocol
from .transcript_repository_protocol import TranscriptRepositoryProtocol
from .user_repository_protocol import UserRepositoryProtocol
