from . import user_repository_protocol as user_repository_protocol
from . import documentation_session_repository_protocol as documentation_session_repository_protocol
from . import audio_record_repository_protocol as audio_record_repository_protocol
from . import transcript_repository_protocol as transcript_repository_protocol
from . import clinical_fact_repository_protocol as clinical_fact_repository_protocol
from . import template_repository_protocol as template_repository_protocol
from . import draft_repository_protocol as draft_repository_protocol
from . import final_document_repository_protocol as final_document_repository_protocol
from .user_repository_protocol import UserRepositoryProtocol
from .documentation_session_repository_protocol import DocumentationSessionRepositoryProtocol
from .audio_record_repository_protocol import AudioRecordRepositoryProtocol
from .transcript_repository_protocol import TranscriptRepositoryProtocol
from .clinical_fact_repository_protocol import ClinicalFactRepositoryProtocol
from .template_repository_protocol import TemplateRepositoryProtocol
from .draft_repository_protocol import DraftRepositoryProtocol
from .final_document_repository_protocol import FinalDocumentRepositoryProtocol
