#!/bin/sh
set -e

: "${PG_APP_USERNAME:?missing PG_APP_USERNAME}"
: "${PG_APP_PASSWORD:?missing PG_APP_PASSWORD}"
: "${PG_APP_DATABASE:?missing PG_APP_DATABASE}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PG_APP_USERNAME}') THEN
    CREATE USER ${PG_APP_USERNAME} WITH PASSWORD '${PG_APP_PASSWORD}';
  END IF;
END;
\$\$;

-- Check if database exists first, then create if needed
SELECT 'CREATE DATABASE ${PG_APP_DATABASE} OWNER ${PG_APP_USERNAME}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${PG_APP_DATABASE}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE ${PG_APP_DATABASE} TO ${PG_APP_USERNAME};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${PG_APP_DATABASE}" <<SQL
GRANT USAGE, CREATE ON SCHEMA public TO ${PG_APP_USERNAME};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PG_APP_USERNAME};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${PG_APP_USERNAME};
SQL
