# pyright: reportUnusedCallResult=false
"""Initial migration

Revision ID: 6e1bc3db5a41
Revises:
Create Date: 2026-04-22 16:39:29.182008+03:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e1bc3db5a41"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medical_document_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "documentation_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "AUDIO_UPLOADED",
                "TRANSCRIBED",
                "DRAFT_CREATED",
                "CONFIRMED",
                name="documentationsessionstatus",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_documentation_sessions_user_id", "documentation_sessions", ["user_id"], unique=False)
    op.create_table(
        "template_fields",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.String(length=500), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["medical_document_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audio_records",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["documentation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audio_records_session_id", "audio_records", ["session_id"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("audio_record_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.Enum("RU", name="transcriptlanguage"), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audio_record_id"], ["audio_records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["documentation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_facts",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("transcript_id", sa.UUID(), nullable=False),
        sa.Column("template_field_id", sa.UUID(), nullable=False),
        sa.Column("is_updated_by_user", sa.Boolean(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("source_start_index", sa.Integer(), nullable=False),
        sa.Column("source_end_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["documentation_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_field_id"], ["template_fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_clinical_facts_session_id", "clinical_facts", ["session_id"], unique=False)
    op.create_index("ix_clinical_facts_template_field_id", "clinical_facts", ["template_field_id"], unique=False)
    op.create_index("ix_clinical_facts_transcript_id", "clinical_facts", ["transcript_id"], unique=False)
    op.create_table(
        "medical_documents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("transcript_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "CONFIRMED", name="medicaldocumentstatus"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["documentation_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["medical_document_templates.id"],
        ),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medical_documents_session_id", "medical_documents", ["session_id"], unique=False)
    op.create_index("ix_medical_documents_transcript_id", "medical_documents", ["transcript_id"], unique=False)
    op.create_index("ix_medical_documents_user_id", "medical_documents", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_medical_documents_user_id", table_name="medical_documents")
    op.drop_index("ix_medical_documents_transcript_id", table_name="medical_documents")
    op.drop_index("ix_medical_documents_session_id", table_name="medical_documents")
    op.drop_table("medical_documents")
    op.drop_index("ix_clinical_facts_transcript_id", table_name="clinical_facts")
    op.drop_index("ix_clinical_facts_template_field_id", table_name="clinical_facts")
    op.drop_index("ix_clinical_facts_session_id", table_name="clinical_facts")
    op.drop_table("clinical_facts")
    op.drop_table("transcripts")
    op.drop_index("ix_audio_records_session_id", table_name="audio_records")
    op.drop_table("audio_records")
    op.drop_table("template_fields")
    op.drop_index("ix_documentation_sessions_user_id", table_name="documentation_sessions")
    op.drop_table("documentation_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("medical_document_templates")
    # ### end Alembic commands ###
